database:
  driverClass: org.postgresql.Driver
  validationQuery: "/* MyService Health Check */ SELECT 1"

server:
  type: simple-logging
  applicationContextPath: /
  adminContextPath: /admin
  connector:
    type: http
    port: 80

logging:
  level: INFO
  appenders:
    - type: console
