database:
  url: jdbc:h2:mem:leads;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
  user: leads
  driverClass: org.h2.Driver
  validationQuery: "/* MyService Health Check */ SELECT 1"

logging:
  level: INFO
  appenders:
    - type: console

server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081
